services:
  backend:
    build:
      context: .
    volumes:
      - ./logs:/app/logs
    network_mode: "host"

  db:
    container_name: 'polly_shop_postgres'
    image: 'postgres:14'
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
